# Generated by Django 5.1.7 on 2025-03-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AssetId', models.CharField(max_length=100)),
                ('Manufacturer', models.CharField(max_length=100)),
                ('ModelNumber', models.CharField(max_length=100)),
                ('AssetName', models.CharField(max_length=100)),
                ('SerialNumber', models.CharField(max_length=100)),
                ('Comments', models.CharField(max_length=100)),
                ('AssetCostAmount', models.CharField(max_length=100)),
                ('NetBookValueAmount', models.CharField(max_length=100)),
                ('Ownership', models.CharField(max_length=100)),
                ('InventoryDate', models.CharField(max_length=100)),
                ('DatePlacedInService', models.CharField(max_length=100)),
                ('UsefulLifePeriods', models.CharField(max_length=100)),
                ('AssetType', models.CharField(max_length=100)),
                ('additionalAsJson', models.JSONField()),
            ],
        ),
    ]
