# Generated by Django 5.1.7 on 2025-04-10 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('EdgeCount', models.IntegerField(default=0)),
                ('NodeCount', models.IntegerField(default=0)),
                ('Version', models.IntegerField(blank=True, default=0, null=True)),
                ('User', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='systems', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SystemVersion', models.IntegerField(default=1)),
                ('AssetId', models.CharField(max_length=100)),
                ('Manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('ModelNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('AssetName', models.CharField(blank=True, max_length=100, null=True)),
                ('SerialNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('Comments', models.CharField(blank=True, max_length=100, null=True)),
                ('AssetCostAmount', models.FloatField(blank=True, null=True)),
                ('NetBookValueAmount', models.CharField(blank=True, max_length=100, null=True)),
                ('Ownership', models.CharField(blank=True, max_length=100, null=True)),
                ('InventoryDate', models.CharField(blank=True, max_length=100, null=True)),
                ('DatePlacedInService', models.CharField(blank=True, max_length=100, null=True)),
                ('UsefulLifePeriods', models.CharField(blank=True, max_length=100, null=True)),
                ('AssetType', models.CharField(blank=True, max_length=100, null=True)),
                ('LocationID', models.CharField(blank=True, max_length=100, null=True)),
                ('BuildingNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('BuildingName', models.CharField(blank=True, max_length=100, null=True)),
                ('Floor', models.CharField(blank=True, max_length=100, null=True)),
                ('RoomNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('AdditionalAsJson', models.JSONField(blank=True, null=True)),
                ('Xposition', models.FloatField(blank=True, default=0, null=True)),
                ('Yposition', models.FloatField(blank=True, default=0, null=True)),
                ('system', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='rest.system')),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SystemVersion', models.IntegerField(default=1)),
                ('ConnectionType', models.CharField(max_length=100)),
                ('ConnectionDetails', models.JSONField(blank=True, null=True)),
                ('Device1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections1', to='rest.device')),
                ('Device2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections2', to='rest.device')),
                ('System', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='rest.system')),
            ],
        ),
    ]
