# Generated by hand for ethernet simulation models.
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rest", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="connection",
            name="BandwidthMbps",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="connection",
            name="LatencyMs",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="connection",
            name="IsTrunk",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="connection",
            name="AllowedVlans",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="connection",
            name="ErrorRate",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="device",
            name="DeviceType",
            field=models.CharField(default="generic", max_length=50),
        ),
        migrations.CreateModel(
            name="Port",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("SystemVersion", models.IntegerField(default=1)),
                ("Name", models.CharField(max_length=100)),
                ("Index", models.IntegerField(default=0)),
                ("SpeedMbps", models.IntegerField(default=1000)),
                ("Duplex", models.CharField(default="full", max_length=10)),
                ("IsTrunk", models.BooleanField(default=False)),
                ("AllowedVlans", models.JSONField(blank=True, null=True)),
                ("AccessVlan", models.IntegerField(blank=True, null=True)),
                ("AdminUp", models.BooleanField(default=True)),
                ("Device", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ports", to="rest.device")),
                ("System", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ports", to="rest.system")),
            ],
        ),
        migrations.CreateModel(
            name="TrafficProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("SystemVersion", models.IntegerField(default=1)),
                ("Name", models.CharField(max_length=100)),
                ("Profile", models.JSONField()),
                ("Device", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="traffic_profiles", to="rest.device")),
                ("System", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="traffic_profiles", to="rest.system")),
            ],
        ),
        migrations.CreateModel(
            name="FirewallRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("SystemVersion", models.IntegerField(default=1)),
                ("Action", models.CharField(default="allow", max_length=10)),
                ("Protocol", models.CharField(blank=True, max_length=10, null=True)),
                ("Src", models.CharField(blank=True, max_length=100, null=True)),
                ("Dst", models.CharField(blank=True, max_length=100, null=True)),
                ("SrcPort", models.IntegerField(blank=True, null=True)),
                ("DstPort", models.IntegerField(blank=True, null=True)),
                ("Vlan", models.IntegerField(blank=True, null=True)),
                ("Device", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="firewall_rules", to="rest.device")),
                ("System", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="firewall_rules", to="rest.system")),
            ],
        ),
        migrations.CreateModel(
            name="DeviceSpec",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ModelName", models.CharField(blank=True, max_length=100, null=True)),
                ("PortCount", models.IntegerField(blank=True, null=True)),
                ("SupportedSpeeds", models.JSONField(blank=True, null=True)),
                ("SupportsVlans", models.BooleanField(default=False)),
                ("SupportsPoE", models.BooleanField(default=False)),
                ("AdditionalSpecs", models.JSONField(blank=True, null=True)),
                ("Device", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="device_spec", to="rest.device")),
            ],
        ),
        migrations.CreateModel(
            name="ConfigFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("Name", models.CharField(max_length=200)),
                ("Format", models.CharField(default="yaml", max_length=20)),
                ("RawText", models.TextField()),
                ("ParsedData", models.JSONField(blank=True, null=True)),
                ("UploadedAt", models.DateTimeField(auto_now_add=True)),
                ("System", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="config_files", to="rest.system")),
            ],
        ),
    ]
