# Generated by Django 5.1.7 on 2025-04-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='Version',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
