# Generated by Django 5.1.7 on 2025-04-12 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_alter_system_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='system',
            new_name='System',
        ),
    ]
