# Generated by hand for device IP and online status.
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rest", "0002_ethernet_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="IpAddress",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="device",
            name="IsOnline",
            field=models.BooleanField(default=True),
        ),
    ]
