# Generated by Django 5.1.7 on 2025-03-31 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_alter_device_assetcostamount_alter_device_assetname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='additionalAsJson',
            new_name='AdditionalAsJson',
        ),
        migrations.AddField(
            model_name='device',
            name='BuildingName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='BuildingNumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='Floor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='LocationID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='RoomNumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='AssetCostAmount',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='NetBookValueAmount',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
