# Generated by Django 5.1.7 on 2025-03-31 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_rename_additionalasjson_device_additionalasjson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='AssetCostAmount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='NetBookValueAmount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
