# Generated by Django 5.1.7 on 2025-04-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0005_alter_device_assetcostamount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='AssetCostAmount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='DatePlacedInService',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
