# Generated by Django 5.1.7 on 2025-04-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0006_alter_device_assetcostamount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='DatePlacedInService',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
