# Generated by Django 5.1.7 on 2025-04-07 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest", "0007_alter_device_dateplacedinservice"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="SystemVersion",
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name="System",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("EdgeCount", models.IntegerField(default=0)),
                ("NodeCount", models.IntegerField(default=0)),
                ("Version", models.JSONField(blank=True, null=True)),
                (
                    "User",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="systems",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Connection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("SystemVersion", models.IntegerField(default=1)),
                ("ConnectionType", models.CharField(max_length=100)),
                ("ConnectionDetails", models.JSONField(blank=True, null=True)),
                (
                    "Device1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connections1",
                        to="rest.device",
                    ),
                ),
                (
                    "Device2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connections2",
                        to="rest.device",
                    ),
                ),
                (
                    "System",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connections",
                        to="rest.system",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="device",
            name="system",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="devices",
                to="rest.system",
            ),
        ),
    ]
