# Generated by Django 5.1.7 on 2025-04-07 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest", "0008_device_systemversion_system_connection_device_system"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="system",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="devices",
                to="rest.system",
            ),
        ),
    ]
