version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    environment:
      - DJANGO_SETTINGS_MODULE=Services.server.settings_prod
      - POSTGRES_DB=${POSTGRES_DB:-navydb}
      - POSTGRES_USER=${POSTGRES_USER:-navyuser}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeThisPassword}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - DEBUG=0
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - SECRET_KEY=${DJANGO_SECRET_KEY:-your-secret-key-change-this}
      - DATABASE_URL=postgres://${POSTGRES_USER:-navyuser}:${POSTGRES_PASSWORD:-changeThisPassword}@db:5432/${POSTGRES_DB:-navydb}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - navy_net

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-navydb}
      POSTGRES_USER: ${POSTGRES_USER:-navyuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeThisPassword}
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-navyuser} -d ${POSTGRES_DB:-navydb}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - navy_net

networks:
  navy_net:
    driver: bridge

volumes:
  pgdata_prod: 